currencies:
  - USD
  - CNY
group:
  logo:
    full:
      width: 400
      height: 300
    thumb:
      width: 133
      height: 100
startup:
  proposal:
    questions:
      en:
        - Product or service introduction.
        - What is the target market?
        - Please provide an estimated operation margin in 5 years (%).
        - What are the competitors currently in the market?
        - What is the advantage of your product or service?
        - What is your marketing plan?
